services:
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: go-auth
    volumes:
      - ./data/db:/var/lib/postgresql/data